import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/common/NavigationBar";
import Footer from "@/components/common/Footer";
import { headers } from "next/headers";
import LayoutWrapper from "@/style/LayoutWrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const h = await headers();
  const pathname = h.get("x-pathname") || "/";
  const PathIsHome = (pathname === "/")

  return (
    <html lang="en">
      <body
        className={`
          ${inter.variable} antialiased`}
      >
        <LayoutWrapper>
          <NavigationBar />
          {children}
          <div className="w-full px-4 sm:px-5 pb-3">
            <Footer />
          </div>
        </LayoutWrapper>
      </body>
    </html>
  );
}
